### ISSUE TITLE
Core container continously restarting

### ISSUE THREAD

**Issue by bingen** [dappnode/DNP_CORE#38]
I'm using version `0.2.13`. In the logs I only see:
```
DAppNodeCore-bind.dnp.dappnode.eth is up-to-date
DAppNodeCore-ipfs.dnp.dappnode.eth is up-to-date
DAppNodeCore-ethchain.dnp.dappnode.eth is up-to-date
DAppNodeCore-ethforward.dnp.dappnode.eth is up-to-date
DAppNodeCore-vpn.dnp.dappnode.eth is up-to-date
DAppNodeCore-wamp.dnp.dappnode.eth is up-to-date
DAppNodeCore-dappmanager.dnp.dappnode.eth is up-to-date
DAppNodeCore-admin.dnp.dappnode.eth is up-to-date
DAppNodeCore-wifi.dnp.dappnode.eth is up-to-date
```

Btw, I see there are newer versions published. How can I upgrade using command line? (Right now I can not access web admin console). I ran `wget -qO - https://installer.dappnode.io | sudo UPDATE=true bash` but looking at the script [it seems it doesn't upgrade core container](https://github.com/dappnode/DAppNode_Installer/blob/master/build/dappnode/scripts/dappnode_install.sh#L57).

**Comment by vdo** [comment]
Hey @bingen  this package is a "meta" package and this script is not meant to upgrade it. The core package endless loop is a bug that should be fixed in latest release. The core package is only installed in upgrades from the UI. Can you try stopping and removing it manually?

**Comment by bingen** [comment]
Hey, yes I stopped and removed it, now I don't see the container anymore, but still can't connect to my dappnode: it doesn't resolve my.dappnode or my.admin.dnp.dappnode.eth (https://github.com/dappnode/DNP_BIND/issues/22), nor can access thru http://172.33.1.9 (https://github.com/dappnode/DNP_ADMIN/issues/384)

**Comment by vdo** [comment]
Ok, let's keep in touch to see if we can spot which is your problem here.

**Comment by bingen** [comment]
I did an update again (`sudo wget -O - https://installer.dappnode.io | sudo UPDATE=true bash`). Everything seems fine now. Closing the issue. Thanks!
